"""
Django settings for inventario project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
import importlib.util

# Detect whether whitenoise is available; make it optional so runserver
# doesn't crash when the package is missing in local dev venvs
USE_WHITENOISE = importlib.util.find_spec('whitenoise') is not None

# Construye rutas dentro del proyecto así: BASE_DIR / 'subdir'.
# BASE_DIR apunta a la carpeta del repositorio que contiene manage.py
BASE_DIR = Path(__file__).resolve().parent.parent


# Ajustes rápidos para desarrollo — no aptos para producción
# Revisar antes de desplegar: SECRET_KEY, DEBUG, ALLOWED_HOSTS
# Ver checklist: https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ADVERTENCIA: mantener la clave secreta fuera del repositorio en producción.
# En producción sobrescribir por variable de entorno o archivo .env y NO commitear.
SECRET_KEY = 'django-insecure-g6cdfwd0hzg5xv_oin*$be^ce-++^h_elh&19j&$&k+j5mkcsf'

# ADVERTENCIA: no dejar DEBUG activado en producción.
# Para producción establecer DEBUG=0 en las variables de entorno (p. ej. en docker-compose).
DEBUG = os.environ.get('DEBUG', '1') == '1'

# Hosts permitidos: por defecto localhost y 127.0.0.1
# En producción configurar ALLOWED_HOSTS como variable de entorno (separada por comas)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bootstrap4',
    'crispy_forms',
    'crispy_bootstrap4',
    'productos',
    'clientes',
    'ventas',
    # allauth
    'allauth',
    'allauth.account',
]

# Notas:
# - `productos`, `clientes`, `ventas` son las aplicaciones principales del proyecto.
# - `allauth` se utiliza únicamente para login; el registro se deshabilita en la configuración.

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
]

# Add WhiteNoise middleware only when the package is installed. This avoids
# raising ModuleNotFoundError on developers' machines that don't have
# whitenoise in their virtualenv.
if USE_WHITENOISE:
    # WhiteNoise permite servir archivos estáticos desde la imagen sin necesidad de nginx
    MIDDLEWARE.append('whitenoise.middleware.WhiteNoiseMiddleware')

MIDDLEWARE += [
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # allauth requires its AccountMiddleware
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Custom middleware to require login for anonymous users
    # Temporarily disabled while debugging redirect loop. Re-enable when fixed.
    'inventario.middleware.LoginRequiredMiddleware',
]

ROOT_URLCONF = 'inventario.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'inventario.context_processors.account_settings',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventario.wsgi.application'


# Database
# Use Postgres when DB_HOST is provided (docker-compose), otherwise fallback to sqlite for local dev
if os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('POSTGRES_DB', 'inventario'),
            'USER': os.environ.get('POSTGRES_USER', 'inventario'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('DB_HOST', 'db'),
            'PORT': os.environ.get('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Nota: cuando se ejecuta en Docker, docker-compose establece DB_HOST=db y se usa Postgres.
# Si ejecutás manage.py localmente sin DB_HOST, se usará sqlite (db.sqlite3).


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
# STATICFILES_DIRS: carpetas adicionales donde buscar archivos estáticos antes de collectstatic
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# STATIC_ROOT: carpeta destino donde collectstatic guarda los archivos para producción
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Si STATICFILES_DIRS apunta a carpetas que no existen verás la advertencia W004.
# Se creó una carpeta `static/` vacía en el repo para evitar esa advertencia.

# Use WhiteNoise storage if available, otherwise fall back to the default
# staticfiles storage so local runserver doesn't crash when whitenoise is
# not installed.
if USE_WHITENOISE:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap4'
CRISPY_TEMPLATE_PACK = 'bootstrap4'

BOOTSTRAP4 = {
    'include_jquery' : True,
    'set_placeholder' : False,
    'required_css_class' : 'required',
    'error_css_class' : 'is-invalid',
    'success_css_class': 'is-valid',
}

# django-allauth and auth settings
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'
ACCOUNT_ALLOW_REGISTRATION = False

# Signup behaviour (we don't ask password twice for custom flows)
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = False

# Where to redirect after logout
# Use concrete paths instead of named URL strings to avoid redirect resolution issues
LOGOUT_REDIRECT_URL = '/accounts/login/'

LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/accounts/login/'

# Middleware to require login site-wide is added below (after AuthenticationMiddleware)
